name = "testagram-cdn"
main = "worker.js"
compatibility_date = "2026-10-08"
workers_dev = false
preview_urls = false

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "testagram-media"

[[routes]]
pattern = "media.testagram.site/*"
zone_name = "testagram.site"

[observability]
enabled = true